# Complete Simulation Chain for Visibility Calculation

## Read in Config

In [1]:
import vipy.simulation.utils as ut
import vipy.layouts.layouts as layouts
import astropy.constants as const
from astropy import units as un
import time as t
import numpy as np

In [2]:
# rc = ut.read_config('/net/nfshome/home/sfroese/vipy/config/default.toml')
rc = ut.read_config("../config/test.toml")
array_layout = layouts.get_array_layout('eht')

src_crd = rc['src_coord']
wave1 = const.c/((float(rc['channel'].split(':')[0])-float(rc['channel'].split(':')[1]))*10**6/un.second)/un.meter
wave2 = const.c/((float(rc['channel'].split(':')[0])+float(rc['channel'].split(':')[1]))*10**6/un.second)/un.meter

## Generate (l,m)-plane / FOV

In [3]:
import vipy.simulation.scan as scan

In [4]:
grid = scan.create_bgrid(rc['fov_size'], 256, src_crd)
lm = scan.lm(grid, src_crd)

## Calculate Start and Stop times for every measurement

In [5]:
time = ut.calc_time_steps(rc)
print(time)

['2016:095:00:00:00.000' '2016:095:00:00:10.000' '2016:095:00:00:20.000'
 '2016:095:00:20:00.000' '2016:095:00:20:10.000' '2016:095:00:20:20.000'
 '2016:095:00:40:00.000' '2016:095:00:40:10.000' '2016:095:00:40:20.000'
 '2016:095:01:00:00.000' '2016:095:01:00:10.000' '2016:095:01:00:20.000'
 '2016:095:01:20:00.000' '2016:095:01:20:10.000' '2016:095:01:20:20.000']


## Calculate Baselines for one measurement

In [9]:
baselines = scan.get_baselines(src_crd, time[0:3], array_layout)

In [10]:
st1,st2 = scan.get_valid_baselines(baselines,28)
st1.shape

(24,)

## Calculate Mueller/Jones matrices

In [11]:
import numpy as np
import torch

In [12]:
%%time
start = t.time()
torch.set_num_threads(8)
JJ_f1 = scan.getJones(lm, baselines, wave1, time[0:3], src_crd, array_layout)
JJ_f2 = scan.getJones(lm, baselines, wave2, time[0:3], src_crd, array_layout)

CPU times: user 15.6 s, sys: 5.03 s, total: 20.6 s
Wall time: 3.66 s


## Open Source Image and compute Stokes vector

In [13]:
from astropy.io import fits
import matplotlib.pyplot as plt
import torch

In [14]:
hdul = fits.open('celestial-03-05.fits')
img = hdul[0].data.astype(np.float32)
img = torch.tensor(img)

I = torch.zeros((img.shape[0],img.shape[1],4), dtype=torch.cdouble)
I[...,0] = img
I[...,1] = img*torch.sqrt(torch.tensor(0.5))
I[...,2] = img*torch.sqrt(torch.tensor(0.5))
# plt.imshow((I[...,1]+I[...,2]).real)
# plt.colorbar()

## Integration

In [15]:
%%time
delta_t = rc['corr_int_time']
delta_f = float(rc['channel'].split(':')[1])*10**6
delta_l = np.abs(lm[255,0,0]-lm[0,0,0])
delta_m = np.abs(lm[0,255,0]-lm[0,0,0])
print(delta_l)

integral = scan.integrate(JJ_f1, JJ_f2, I, 2, delta_t, delta_f, delta_l, delta_m)
integral.shape
end = t.time()
print(end - start)

0.0001830982550547064
4.886212587356567
CPU times: user 4.96 s, sys: 2.12 s, total: 7.07 s
Wall time: 1.04 s


In [16]:
integral.shape

torch.Size([12, 4])

In [17]:
integral

tensor([[ 1.5361e-04+1.9068e-04j,  1.1414e-04+1.4162e-04j,
          7.3597e-05+9.1274e-05j,  5.4686e-05+6.7790e-05j],
        [-2.8102e-05-3.3827e-05j, -5.9045e-06-7.1092e-06j,
         -2.1364e-04-2.5706e-04j, -4.4891e-05-5.4023e-05j],
        [-2.5165e-04-3.9236e-05j, -1.8750e-04-2.9215e-05j,
         -1.9086e-03-2.9781e-04j, -1.4220e-03-2.2175e-04j],
        [-4.0103e-05-3.6748e-05j, -1.9255e-05-1.7631e-05j,
         -3.0474e-04-2.7937e-04j, -1.4632e-04-1.3404e-04j],
        [ 8.5381e-04+1.6212e-03j,  1.7994e-04+3.4074e-04j,
          6.3850e-04+1.2062e-03j,  1.3456e-04+2.5352e-04j],
        [-5.4484e-04-4.4131e-04j, -1.1451e-04-9.2606e-05j,
         -2.6166e-04-2.1069e-04j, -5.4996e-05-4.4211e-05j],
        [-5.4564e-04+1.0468e-04j, -4.8685e-04+1.1854e-04j,
         -3.6608e-04+1.0255e-04j, -3.2891e-04+1.0475e-04j],
        [ 1.3345e-05-2.3824e-05j,  3.0863e-06-5.5094e-06j,
          8.3098e-05-1.4835e-04j,  1.9137e-05-3.4165e-05j],
        [-2.1100e-04+1.8348e-04j, -1.4940e-04+1.

## All scan loop

In [18]:
from tqdm import tqdm

In [19]:
torch.set_num_threads(12)

In [20]:
hdul = fits.open('celestial-03-05.fits')
img = hdul[0].data.astype(np.float32)
img = torch.tensor(img)

I = torch.zeros((img.shape[0],img.shape[1],4), dtype=torch.cdouble)
I[...,0] = img
I[...,1] = img*torch.sqrt(torch.tensor(0.5))
I[...,2] = img*torch.sqrt(torch.tensor(0.5))

In [32]:
integral2 = np.array([])
#i in total number of scans
for i in tqdm(range(5)):
    t = time[i*2:(i+1)*2+1]
    print(t)
    baselines = scan.get_baselines(src_crd, t, array_layout)
    
    JJ_f1 = scan.getJones(lm, baselines, wave1, time, src_crd, array_layout)
    if JJ_f1.shape[0] == 1:
        continue
    JJ_f2 = scan.getJones(lm, baselines, wave2, time, src_crd, array_layout)
    print(JJ_f1.shape)

    delta_t = rc['corr_int_time']
    delta_f = float(rc['channel'].split(':')[1])*10**6
    delta_l = np.abs(lm[255,0,0]-lm[0,0,0])
    delta_m = np.abs(lm[0,255,0]-lm[0,0,0])

    integral2 = np.append(integral2,scan.integrate(JJ_f1, JJ_f2, I, 2, delta_t, delta_f, delta_l, delta_m))
    print(scan.integrate(JJ_f1, JJ_f2, I, 1, delta_t, delta_f, delta_l, delta_m).shape)


  0%|          | 0/5 [00:00<?, ?it/s]

['2016:095:00:00:00.000' '2016:095:00:00:10.000' '2016:095:00:20:00.000']
torch.Size([256, 256, 24, 4, 4])


 20%|██        | 1/5 [00:01<00:04,  1.00s/it]

torch.Size([12, 4])
['2016:095:00:20:00.000' '2016:095:00:20:10.000' '2016:095:00:40:00.000']
torch.Size([256, 256, 24, 4, 4])


 40%|████      | 2/5 [00:02<00:03,  1.01s/it]

torch.Size([12, 4])
['2016:095:00:40:00.000' '2016:095:00:40:10.000' '2016:095:01:00:00.000']
torch.Size([256, 256, 24, 4, 4])


 60%|██████    | 3/5 [00:03<00:01,  1.00it/s]

torch.Size([12, 4])
['2016:095:01:00:00.000' '2016:095:01:00:10.000' '2016:095:01:20:00.000']
torch.Size([256, 256, 40, 4, 4])


 80%|████████  | 4/5 [00:04<00:01,  1.22s/it]

torch.Size([20, 4])
['2016:095:01:20:00.000' '2016:095:01:20:10.000' '2016:095:01:20:20.000']
torch.Size([256, 256, 40, 4, 4])


100%|██████████| 5/5 [00:06<00:00,  1.23s/it]

torch.Size([20, 4])


In [33]:
integral2 = integral2.reshape(-1, 4)
integral2.shape

(76, 4)

In [34]:
integral2

array([[ 1.53612912e-04+1.90676858e-04j,  1.14141964e-04+1.41617721e-04j,
         7.35971100e-05+9.12743597e-05j,  5.46863521e-05+6.77900933e-05j],
       [-2.81016866e-05-3.38269830e-05j, -5.90445952e-06-7.10919705e-06j,
        -2.13643069e-04-2.57056346e-04j, -4.48905846e-05-5.40232160e-05j],
       [-2.51645339e-04-3.92361397e-05j, -1.87497392e-04-2.92152935e-05j,
        -1.90856773e-03-2.97810937e-04j, -1.42204827e-03-2.21749209e-04j],
       [-4.01032835e-05-3.67480763e-05j, -1.92551676e-05-1.76313124e-05j,
        -3.04738211e-04-2.79365748e-04j, -1.46316355e-04-1.34036772e-04j],
       [ 8.53807532e-04+1.62116446e-03j,  1.79940639e-04+3.40743147e-04j,
         6.38499054e-04+1.20616109e-03j,  1.34562658e-04+2.53517201e-04j],
       [-5.44844334e-04-4.41314528e-04j, -1.14514940e-04-9.26056523e-05j,
        -2.61663928e-04-2.10690580e-04j, -5.49958281e-05-4.42107643e-05j],
       [-5.45635177e-04+1.04681529e-04j, -4.86854008e-04+1.18536333e-04j,
        -3.66077806e-04+1.025525

In [35]:
integral == integral2

False

In [37]:
torch.isclose(integral, torch.tensor(integral2), rtol=1e-3)

tensor([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [Fal